# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jumpstarter
email: exponenthash@gmail.com
description: "Great web agency offers high impact yet affordable web development services. From web design to targeted SEO to custom web applications."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # nthe base hostname & protocol for your site
twitter_username: anshul81
github_username:  anshulfreelancer

# Build settings
markdown: kramdown

permalink: none
comments: true 
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Your name"
      category: "jekyll"
